### PR TITLE
CustomSettingNames.xml: Import Stereo Settings from DarkStarSword's 3…

### PR DESCRIPTION
**Pull request by DarkStarSword**
…d-fixes repository

This commit imports the changes to the CustomSettingNames.xml used by
the 3D Vision automatic driver. Most of the setting names were extracted
from a table in the driver - refer to DarkStarSword's 3d-fixes
repository for the script used to extract these. Additional research
into these settings is documented here:

http://wiki.bo3b.net/index.php?title=Driver_Profile_Settings

This commit should be equivelent to the final combination of the below
listed commits, applied on top of the equivelent file in this
repository. The history in the original repository can be found here:

https://github.com/DarkStarSword/3d-fixes/commits/master/CustomSettingNames_en-EN.xml

commit e9a9768557cfcc531a38360fc625984870805132
Author: Ian Munsie <darkstarsword@gmail.com>
Date:   Wed Jun 10 23:49:33 2015 +1000

    Update StereoTextureEnable in CustomSettingNames

commit 650d81cb0b4cd199e4e5952faefe28d5f0188464
Author: Ian Munsie <darkstarsword@gmail.com>
Date:   Sun Feb 22 12:28:54 2015 +1100

    CustomSettingNames_en-EN.xml: Update with new settings from 344.75

    Looks like several new settings to support VRDirect

commit ceb5f4b9c1bd4038f3c05ba8d2b3577a863796ab
Author: Ian Munsie <darkstarsword@gmail.com>
Date:   Mon Oct 20 10:27:34 2014 +1100

    nVidia Inspector Custom Setting Names: Add Near/Far for StereoCutoff

    Seems to use the entire low byte, but I found a log function in the DLL
    that explicitly notes 2 as 'Near' and anything else as 'Far'.

commit ff7861a8e4e15e2f237f8b586796ccddd84f3fcc
Author: Ian Munsie <darkstarsword@gmail.com>
Date:   Sat Oct 18 22:59:53 2014 +1100

    nVidia Inspector Custom Setting Names: Merge all stereo settings from driver

    The only setting I've identified that wasn't in the driver table was
    0x701EB457, the existence of which allows stereo to kick in in Windowed
    mode.

commit 64faacd164a3c6e033c8c5c75552ee9f78651aea
Author: Ian Munsie <darkstarsword@gmail.com>
Date:   Fri Oct 17 14:49:00 2014 +1100

    nVidia Inspector: Rename "Stereo Tweaks 2" to "StereoShaderMatrixCheck"

    Cygnific found this name in nvwgf2um.dll

commit adcbb2936c00bd34482dc79a3d973a8492c93b62
Author: Ian Munsie <darkstarsword@gmail.com>
Date:   Fri Oct 10 00:16:17 2014 +1100

    nVidia Inspector: Identified setting that allows Windowed 3D

    Strange thing is it doesn't seem to matter what value it's set to - only that
    the attribute exists (i.e. is not greyed out) in the profile.

    Tested with Journey of a Roach in Windowed mode.

commit 9c654e5251fd1f4203095ab0fa187b62d50dade4
Author: Ian Munsie <darkstarsword@gmail.com>
Date:   Thu Oct 9 23:27:53 2014 +1100

    nVidia Inspector: Things discovered experimenting with Miasmata

    I was able to identify the following data points:

    - Setting 0x70E34A78 ("Stereo Tweaks 2") to any* non-zero value fixed the halo
      on the water.
      * I tried 0x00000000, 0xffffffff, 0xffff0000, 0x0000ffff, 0x0000000f,
        0x00000001 and 0x00000002

    - Setting 0x709A1DDF to 0 broke (offset) shadows in Miasmata.

    - Setting 0x70EDB381 to 0 rendered the game monoscopic - however 3D vision did
      seem to kick in and toggling it showed things moved, as though only one eye
      was being rendered.

    - Miasmata enabled 3D in windowed mode no matter what I changed.

    Further experimentation may reveal additional clues about these settings.

commit 3edb047c9f60eb0e59983788aa646f03229827bd
Author: Ian Munsie <darkstarsword@gmail.com>
Date:   Thu Oct 9 22:50:21 2014 +1100

    nVidia Inspector: Add unidentified attributes from Aion & Prototype 2

    The idea is to make it easier to experiment with these in other games... I
    don't know what does what yet.

commit 49761985a4d923bafb6ea39819e7430854efc014
Author: Ian Munsie <darkstarsword@gmail.com>
Date:   Thu Oct 9 22:21:19 2014 +1100

    nVidia Inspector: Name 3D Notes and convergence attributes

    nVidia Inspector seems to have some bugs reading string fields, so I'm not 100%
    sure that the 3D Notes fields are correct - some games seem to have 3D notes in
    those fields, others have gibberish. Editing it doesn't seem to work, and it
    wouldn't surprise me if they are all wrong.

    Convergence was confirmed by comparing the value saved in the Miasmata profile
    with the value we force in DX9Settings.ini, then setting it to different values
    (such as 0) and confirming that it changed in game.

    Show 3D Notes was determined by reverting all custom settings and noting that
    the notes turned on, then turning them off in-game and noting which attribute
    got set to 0x00000000. Further experimentation confirmed this was the correct
    attribute.

commit 59c5cddef3bb20e2801e384246e21dcb54e28493
Author: Ian Munsie <darkstarsword@gmail.com>
Date:   Thu Oct 9 22:17:32 2014 +1100

    Add nVidia Inspector Custom Setting Names XML

    I'm about to edit this and want to track my changes.

### CODE REVIEW

**Comment by Orbmu2k** [comment]
there is an implementation included which parses the NvD3dUmx.dll from the given system ;-)
nvidiaProfileInspector/nspector/Common/Meta/NvD3dUmxSettingMetaService.cs 

those setting names will be shown already, you may have to toggle the toolbutton "Show unknown setttings from NVIDIA predefined profiles"

please only add settings to "CustomSettingsNames.xml" which are kind of common to average users and full known and providing a bunch of useful values! 

for guessed values and semi known settings which are not already provided by any of the meta services you can make use of "Reference.xml" which is the same format as "CustomSettingNames.xml", but only shown if either the setting is set in the selected profile or you have toggled the view to "Show unknown setttings from NVIDIA predefined profiles"

**Comment by DarkStarSword** [comment]
Ok, good to know - I missed that new functionality :)

I might send a revised pull request later with that info in mind, as many of those are either non-functional or only partially functional without also having a value in setting 0x701EB457 (which we refer to as the "mystery stereo setting" in the modding community since we cannot find an official name for it). Do you have a preferred name for this?

As for other common options - StereoFlagsDX10 is a must (set to 0x00004000 is required for most DX11 games that use compute shaders as part of the rendering pipeline). Tweaking StereoTextureEnable and StereoUseMatrix are also quite important for certain games. Users also like to tweak LaserSightEnabled, LaserXAdjust and LaserYAdjust.

Users also like to tweak 2DDHUDSettings, however the driver ignores that setting if the internal settings flag is not set so everyone is currently using Geforce Profile Manager to edit that one.

**Comment by Orbmu2k** [comment]
The setting 0x701EB457 is just called STEREO_STEREOPROFILE, you can simply use "StereoProfile"

**Comment by DarkStarSword** [comment]
Thanks. Where did you find that name btw?

**Comment by DarkStarSword** [comment]
BTW I spotted two more tables in the dll with alternate IDs for some of those settings in - they are just above the table with the names. List here:
http://wiki.bo3b.net/index.php?title=Driver_Profile_Settings#Notes_on_settings_with_multiple_IDs

**Pull request closed without merging**
