### PR TITLE
Update API to R510, clean-ups, bug fixes and update framework to 4.8.

### PR DESCRIPTION
**Pull request by FoulPlay**

### CODE REVIEW

**Comment by Orbmu2k** [comment]
just no! you can not just apply totally different code style for all files. this ist not how contribution works. 

what are the benefits from your pull request for the main project? .net 4.8 and newer api? this is 30sec work.

also claiming credits in the title for just nothing?

**Comment by FoulPlay** [comment]
I been told to do this from SpecialK's discord and I forgot to delete this pull request.

I'm not a software developer and I am using a unknown to me IDE called Jetbrain's Rider and
 the IDE did the codestyle change and reformatted everything as I did not do this manually.

Don't be a dick about this, 4.8 Framework fixed framework errors with some people and the newer API and updating this program is because I was sick of waiting for you to update this program. 
You disappeared for 16 months so don't disappear for 16 months when your program is so necessary to everyone with Nvidia cards and you have a responsibility to maintain this and keep it up to date with the newer drivers. If you cannot keep this updated, archive this project and let someone else do it.

**Comment by garoto** [comment]
I understand the frustration when a piece of software one comes to consider essential isn't quite keeping up or whatever, but your approach to this PR seems a bit misguided. Plus, you can always use your "updated" fork no?

**Comment by FoulPlay** [comment]
Being honest, I might be deleting my fork and reforking this as I'm learning about the Jetbrain's Rider IDE. This IDE is very confusing and I don't understand it a lot. The PR was a suggestion by a Discord member. I forgot to delete it.

**Pull request closed without merging**
